### ISSUE TITLE
Version for Delphi XE2

### ISSUE THREAD

**Issue by gidesa** [Dennis1000/verysimplelua#12]
Hello,
thanks for your very nice units.
I adapted them to work with Delphi XE2. The only modifications required are:
1) substitute $ENDIF with $IFEND in the conditional compilation beginning with $IF defined(...)

2) insert this conditional block in VerySimple.Lua.Lib in Interface types part:
// Compile for Delphi <= XE2
{$IF CompilerVersion<=23}
  MarshaledAString = PAnsiChar;
  PMarshaledAString = ^PAnsiChar;
  TMarshString = record
    s: string;
    function ToPointer(): PAnsiChar;
  end;
  TMarshaller = record
    s: string;
    function AsAnsi(s: string): TMarshString;
  end;
{$ifend}

3) insert this conditional block in VerySimple.Lua.Lib under Implementation part:
// Compile for Delphi <= XE2
{$IF CompilerVersion<=23}
  function TMarshString.ToPointer(): PAnsiChar;
  begin
    Result:=PAnsiChar(AnsiString(s));
  end;
  function TMarshaller.AsAnsi(s: string): TMarshString;
  var
    ms: TMarshString;
  begin
    ms.s:= s;
    Result:= ms;
  end;
{$ifend}

Of course it emulates types MarshaledAString and TMarshaller that are present only in newer versions of Delphi.
Regards

Giandomenico De Sanctis

**Comment by Entomologen** [comment]
Very interesting. As I understand your comment, you've actually got your cpp files throught the compiler? I can't say I'm an expert on C++ Builder - I've turned back to Delphi. I've tried like a hundred different setups to get VerySimpleLua to complie with XE8. But no matter what settings I choose, I get too many errors.
/ Johan

3 november 2020 15:11:36 +01:00, skrev gidesa <notifications@github.com>:

**Comment by gidesa** [comment]
No, I don't have compiled under CPP, I work only with Delphi XE2, Personal version. In the VerysimpleLua sources there are no CPP files.
I have modified only the parts in VerySimple.Lua.Lib, noted in the first message, and the ending tag for "$IFDEF defined(...)", because Delphi XE2 require $IFEND as closing tag, not $ENDIF.
With that changes VerysimpleLua compile under Delphi XE2, and all demo work without problems.
Regards

Giandomenico

**Comment by Dennis1000** [comment]
Issue outdated and closed.
