### ISSUE TITLE
Wrong function declaration: lua_testudata

### ISSUE THREAD

**Issue by efortier** [Dennis1000/verysimplelua#2]
The function reads as such:

`procedure luaL_testudata(L: lua_State; ud: Integer; const tname: MarshaledAString);`

However the lua 5.3 documentation declares it with a return type of `void *`. I suggest this change:

`function luaL_testudata(L: lua_State; ud: Integer; const tname: MarshaledAString): Integer;`

Thanks for your great work in translating the C headers, it helped me tremendously.

**Comment by Dennis1000** [comment]
Thank you, fixed. I've used a Pointer instead of Integer (64 bit compatibility).
