### ISSUE TITLE
Lazarus Support ?

### ISSUE THREAD

**Issue by mahdix18** [Dennis1000/verysimplelua#8]

**Comment by zaher** [comment]
Lazarus have package for Lua, but i still like verysimplelua more, but by looking inside the code, it needs alot of modification for string encoding, that maybe break stability.

**Comment by Dennis1000** [comment]
@zaher: Could you give a short example what would not work with Lazarus/FPC and how to rewrite it? I'm currently working on v3.0 that supports Lua 5.4.0 (90% done), maybe I'll take a look on FPC compatibility, too.

**Comment by zaher** [comment]
I don't remember in fact, but If you interested I will make work with Lazarus and add pull request, just need permission, i will try to make modification as less as i can.

**Comment by Dennis1000** [comment]
please wait for the v3.0 release, as I'm rewriting some parts.

**Comment by Dennis1000** [comment]
Issue outdated and closed.
